### PR TITLE
Updated to new PokeGOAPI version (0.3) for issue #25

### PR DESCRIPTION
**Pull request by Ljaysoft**
Refactored code to use the latest version of PokeGOAPI (mainly to be able to use items)

### CODE REVIEW

**Comment by weblue** [comment]
requesting not to merge until after #19 is merged

**Comment by ghost** [comment]
I have merged #19. I'll merge this one once the conflicts are resolved  (Btw, is this something that i can do myself, or?)

**Comment by Ljaysoft** [comment]
Currently having trouble with merging.. I hate github sometimes :S

**Comment by ghost** [comment]
Wonderful, thanks!

**Pull request merged**
