### PR TITLE
Optimisations and Logout

### PR DESCRIPTION
**Pull request by Ljaysoft**
Added a logout button in the File menu.
Removed MutableInt class (not needed).
refactored the BlossomsPoGoManager to have login/logout(actually relog) functions.

### CODE REVIEW

**Comment by weblue** [comment]
I believe the logout function covers it. It's been added to menubar

Nevermind, that was just added

**Comment by weblue** [comment]
Is multiple accounts going to be supported? It would be easy enough since it's already a tab layout

**Comment by ghost** [comment]
Well, It depends on what direction the project takes. The reason it was originally tabbed is so that we can have an inventory tab as well, so you could do things like use lucky eggs, or whatever you need to do to your inventory.

**Comment by weblue** [comment]
Other than lucky eggs, what did you have in mind for the other tab? Trainer info could also go there, but inventory management is handled fairly well in the app.

**Comment by ghost** [comment]
No, you have a good point. We'll go ahead and merge this PR, i just tested it out and it looks pretty good :) Thanks for the help

**Comment by Ljaysoft** [comment]
About the inventory, I'm currently making a tab to use items (mainly only lucky egg atm), but I guess  you could use it to use potions and revive as well.

**Pull request merged**
