### PR TITLE
Fixed a bunch of imports and removed the target/class folder

### PR DESCRIPTION
**Pull request by Ljaysoft**
Fixed a bunch of imports and removed the target/class folder

### CODE REVIEW

**Comment by ghost** [comment]
Hey thank you for scouring the project and all, I really do appreciate it. However, is it 100% necessary to make the formatting changes?

**Comment by Ljaysoft** [comment]
Oops, didn't mean to put the reformatting change in this commit

**Comment by Ljaysoft** [comment]
Reverted the reformatting. Will make a new branch so it won't affect the pull.

**Comment by ghost** [comment]
One other thing before i can accept this, the mutable int is actually my own custom class (i had no idea that was already a thing haha), and my json imports are modified from the source(edit: what i mean is i'll provide the json classes). Fix those, and it will work when i merge my utilities classes into this project.

**Comment by weblue** [comment]
Could we get access to your utilities class?

**Comment by ghost** [comment]
Absolutely, thats what im going to do next. To be honest though, I am not familiar with using github with multiple people trying to make changes at the same time. How does any of that work anyways? I'd hate to overwrite any changes, but i also dont want to move forwards without accepting the gitignore and maven fixes.

**Comment by weblue** [comment]
Github will ask to resolve conflicts before the code can be merged. If you
dont have the full source though, github wont know there's a conflict.

On Aug 2, 2016 3:46 PM, "Corrie Blossom Kay" notifications@github.com
wrote:

Absolutely, thats what im going to do next. To be honest though, I am not
familiar with using github with multiple people trying to make changes at
the same time. How does any of that work anyways? I'd hate to overwrite any
changes, but i also dont want to move forwards without accepting the
gitignore and maven fixes.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/Blossomforth/BlossomsPokemonGoManager/pull/11#issuecomment-237020917,
or mute the thread

**Comment by ghost** [comment]
Okay, so I have to make these changes first, and then Ljaysoft can then re-submit their changes?

**Comment by Ljaysoft** [comment]
I reverted the json dependancy, even tho I think it's still better to do that than have your own library of json included.. no?

**Comment by ghost** [comment]
No, i'm sorry, you're right. I just realized that the changes that I made were not being used. Terribly sorry, but you can put that back in if you want.

**Comment by Ljaysoft** [comment]
Done, it's not a big change anyway ;)

**Pull request merged**
